config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :subprojects
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "projects#index"
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :client_subprojects, class_name: 'Subproject', foreign_key: 'client_id'
  has_many :owner_subprojects, class_name: 'Subproject', foreign_key: 'owner_id'
  has_many :builder_subprojects, class_name: 'Subproject', foreign_key: 'builder_id'

  validates :company_name, :firstname, :lastname, :email, presence: true
  validates :email, uniqueness: true

  def referenced_count
    owner_subprojects.count + builder_subprojects.count + client_subprojects.count
  end

  def editable?
    referenced_count <= 1
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy!

    respond_to do |format|
      format.html { redirect_to clients_path, status: :see_other, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.expect(client: [ :company_name, :firstname, :lastname, :streetname, :zipcode, :city, :country, :email, :phone ])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Company name:</strong>
    <%= client.company_name %>
  </p>

  <p>
    <strong>Firstname:</strong>
    <%= client.firstname %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= client.lastname %>
  </p>

  <p>
    <strong>Streetname:</strong>
    <%= client.streetname %>
  </p>

  <p>
    <strong>Zipcode:</strong>
    <%= client.zipcode %>
  </p>

  <p>
    <strong>City:</strong>
    <%= client.city %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= client.country %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= client.phone %>
  </p>

</div>

app/views/clients/_form.html.erb
<% if @client.editable? %>
  <%= form_with(model: client) do |form| %>
    <% if client.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

        <ul>
          <% client.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% [:company_name, :firstname, :lastname, :streetname, :zipcode, :city, :country, :email, :phone].each do |attrib|%>
      <div>
        <%= form.label attrib, style: "display: block" %>
        <%= form.text_field attrib %><br>
      </div>
    <% end %>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% else %>
  <p>This client is used in multiple subprojects and cannot be edited.</p>
<% end %>

app/views/clients/edit.html.erb
<% content_for :title, "Editing client" %>

<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Clients" %>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

<%= link_to "Back to main", "/" %>

app/views/clients/new.html.erb
<% content_for :title, "New client" %>

<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>