config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :subprojects
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :subprojects, inverse_of: :project
  accepts_nested_attributes_for :subprojects, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.includes(:subprojects => [:client, :owner, :builder]).all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.subprojects.build
    @project.subprojects.each do |subproject|
      subproject.build_client
      subproject.build_owner
      subproject.build_builder
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  CLIENT_FIELDS = [:company_name, :firstname, :lastname, :streetname, :zipcode, :city, :country, :email, :phone]

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(
        :name, :email, :short_name,
        subprojects_attributes: [
          :id, :subproject_name, :client_id, :owner_id, :builder_id, :_destroy,
          client_attributes: CLIENT_FIELDS,
          owner_attributes: CLIENT_FIELDS,
          builder_attributes: CLIENT_FIELDS
        ]
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% [:name, :email, :short_name, :offer_date, :order_date].each do |prj_attrib| %>
  <div>
    <%= form.label prj_attrib, style: "display: block" %>
    <%= form.text_field prj_attrib %>
  </div>
  <% end %>

  <h3>Subprojects</h3>
  <%= form.fields_for :subprojects do |sp_form| %>
    <div class="subproject-fields">
      <%= sp_form.label :subproject_name %>
      <%= sp_form.text_field :subproject_name %>

      <% [:client, :owner, :builder].each do |role| %>
        <div>
          <%= sp_form.label "#{role}_id", "Select Existing #{role.capitalize}" %>
          <%= sp_form.collection_select "#{role}_id", Client.all, :id, -> (client) { "#{client.company_name} (#{client.lastname}, #{client.firstname})" }, prompt: "Select #{role.capitalize}" %>

          <fieldset>
            <legend>Or Create New <%= role.capitalize %></legend>
            <%= sp_form.fields_for role do |c_form| %>
              <% [:company_name, :firstname, :lastname, :streetname, :zipcode, :city, :country, :email, :phone].each do |attrib| %>
                <%= c_form.label attrib %>
                <%= c_form.text_field attrib %><br>
              <% end %>
            <% end %>
          </fieldset>
        </div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.email %> <%= project.name %>
  </p>

  <% if project.subprojects.any? %>
    <ul>
      <% project.subprojects.each do |subproject| %>
        <li>
          <%= link_to "#{subproject.subproject_name}", subproject_path(subproject) %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No subprojects</p>
  <% end %>

</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>