config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :subprojects
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "projects#index"
end

app/models/subproject.rb
class Subproject < ApplicationRecord
  belongs_to :project

  belongs_to :client, class_name: 'Client', optional: true
  belongs_to :owner, class_name: 'Client', optional: true
  belongs_to :builder, class_name: 'Client', optional: true

  accepts_nested_attributes_for :client, reject_if: :all_blank
  accepts_nested_attributes_for :owner, reject_if: :all_blank
  accepts_nested_attributes_for :builder, reject_if: :all_blank

  validates :subproject_name, presence: true
  validate :client_presence_check
  validate :owner_presence_check
  validate :builder_presence_check

  validates_associated :client, :owner, :builder

  def client_attributes=(attributes)
    self.client = Client.find_or_initialize_by(email: attributes[:email])
    self.client.assign_attributes(attributes)
  end

  def owner_attributes=(attributes)
    self.owner = Client.find_or_initialize_by(email: attributes[:email])
    self.owner.assign_attributes(attributes)
  end

  def builder_attributes=(attributes)
    self.builder = Client.find_or_initialize_by(email: attributes[:email])
    self.builder.assign_attributes(attributes)
  end

  private

  def client_presence_check
    if client_id.blank? && (client_attributes_blank?)
      errors.add(:client, "must be selected or a new client must be provided")
    end
  end

  def owner_presence_check
    if owner_id.blank? && (owner_attributes_blank?)
      errors.add(:owner, "must be selected or a new owner must be provided")
    end
  end

  def builder_presence_check
    if builder_id.blank? && (builder_attributes_blank?)
      errors.add(:builder, "must be selected or a new builder must be provided")
    end
  end

  def client_attributes_blank?
    return true if client.nil?
    client.attributes.except("id", "created_at", "updated_at").values.all?(&:blank?)
  end

  def owner_attributes_blank?
    return true if client.nil?
    owner.attributes.except("id", "created_at", "updated_at").values.all?(&:blank?)
  end

  def builder_attributes_blank?
    return true if client.nil?
    builder.attributes.except("id", "created_at", "updated_at").values.all?(&:blank?)
  end

end

app/controllers/subprojects_controller.rb
class SubprojectsController < ApplicationController
  before_action :set_subproject, only: %i[ show edit update destroy ]

  # GET /subprojects or /subprojects.json
  def index
    @subprojects = Subproject.includes(:client).all
  end

  # GET /subprojects/1 or /subprojects/1.json
  def show
  end

  # GET /subprojects/new
  def new
    @subproject = Subproject.new
  end

  # GET /subprojects/1/edit
  def edit
  end

  # POST /subprojects or /subprojects.json
  def create
    @subproject = Subproject.new(subproject_params)

    respond_to do |format|
      if @subproject.save
        format.html { redirect_to @subproject, notice: "Subproject was successfully created." }
        format.json { render :show, status: :created, location: @subproject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subprojects/1 or /subprojects/1.json
  def update
    respond_to do |format|
      if @subproject.update(subproject_params)
        format.html { redirect_to @subproject, notice: "Subproject was successfully updated." }
        format.json { render :show, status: :ok, location: @subproject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subprojects/1 or /subprojects/1.json
  def destroy
    @subproject.destroy!

    respond_to do |format|
      format.html { redirect_to subprojects_path, status: :see_other, notice: "Subproject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subproject
      @subproject = Subproject.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def subproject_params
      params.expect(subproject: [ :subproject_name, :project_id, :client_id, :owner_id, :builder_id ])
    end
end

app/helpers/subprojects_helper.rb
module SubprojectsHelper
end

app/views/subprojects/_form.html.erb
<%= form_with(model: subproject) do |form| %>
  <% if subproject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subproject.errors.count, "error") %> prohibited this subproject from being saved:</h2>

      <ul>
        <% subproject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :subproject_name, style: "display: block" %>
    <%= form.text_field :subproject_name %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.label :owner_id, style: "display: block" %>
    <%= form.text_field :owner_id %>
  </div>

  <div>
    <%= form.label :builder_id, style: "display: block" %>
    <%= form.text_field :builder_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subprojects/_subproject.html.erb
<div id="<%= dom_id subproject %>">
  <p>
    <strong>Subproject name:</strong>
    <%= subproject.subproject_name %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= subproject.project_id %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= link_to "#{subproject.client&.company_name} (#{subproject.client&.lastname}, #{subproject.client&.firstname})", client_path(subproject.client&.id) %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= link_to "#{subproject.owner&.company_name} (#{subproject.owner&.lastname}, #{subproject.owner&.firstname})", client_path(subproject.owner&.id) %>
  </p>

  <p>
    <strong>Builder:</strong>
    <%= link_to "#{subproject.builder&.company_name} (#{subproject.builder&.lastname}, #{subproject.builder&.firstname})", client_path(subproject.builder&.id) %>
  </p>

</div>

app/views/subprojects/edit.html.erb
<% content_for :title, "Editing subproject" %>

<h1>Editing subproject</h1>

<%= render "form", subproject: @subproject %>

<br>

<div>
  <%= link_to "Show this subproject", @subproject %> |
  <%= link_to "Back to subprojects", subprojects_path %>
</div>

app/views/subprojects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Subprojects" %>

<h1>Subprojects</h1>

<div id="subprojects">
  <% @subprojects.each do |subproject| %>
    <%= render subproject %>
    <p>
      <%= link_to "Show this subproject", subproject %>
    </p>
  <% end %>
</div>

<%= link_to "New subproject", new_subproject_path %>

<%= link_to "Back to main", "/" %>

app/views/subprojects/new.html.erb
<% content_for :title, "New subproject" %>

<h1>New subproject</h1>

<%= render "form", subproject: @subproject %>

<br>

<div>
  <%= link_to "Back to subprojects", subprojects_path %>
</div>

app/views/subprojects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subproject %>

<div>
  <%= link_to "Edit this subproject", edit_subproject_path(@subproject) %> |
  <%= link_to "Back to subprojects", subprojects_path %>

  <%= button_to "Destroy this subproject", @subproject, method: :delete %>
</div>